markdown: kramdown
permalink: /:title/
url: http://sdr-x.github.io
name: SDR-X
author: "Jiao Xianjun"
qq: 
email: putaoshu@gmail.com
duoshuo: jxj
beian: 
cnzz: 
weibo: spaceshuttle
github: JiaoXianjun
pygments: true
safe: true
paginate: 20
about: "Jiao Xianjun's tech blog."
